# Generated by Django 5.0.4 on 2024-04-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fcmToken', models.CharField(max_length=500)),
                ('expiredAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.IntegerField()),
                ('regionName', models.CharField(max_length=100)),
                ('regionType', models.CharField(choices=[('State', 'State'), ('District', 'District'), ('Community', 'Community'), ('none', None)], max_length=100)),
                ('childrenOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.region')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveAlarm',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('type', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('AIR', 'AIR'), ('ARTILLERY', 'ARTILLERY'), ('URBAN_FIGHTS', 'URBAN_FIGHTS'), ('CHEMICAL', 'CHEMICAL'), ('NUCLEAR', 'NUCLEAR'), ('INFO', 'INFO')], max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.region')),
            ],
        ),
    ]
