# Generated by Django 5.0.4 on 2024-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.IntegerField()),
                ('regionName', models.CharField(max_length=100)),
                ('regionType', models.CharField(choices=[('state', 'state'), ('city', 'city'), ('district', 'district'), ('none', None)], max_length=100)),
            ],
        ),
    ]
