# Generated by Django 5.0.4 on 2024-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_activealarm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfcmtoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='app_version_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='device_android_sdk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='os_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='user_login',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
    ]
