# Generated by Django 5.0.4 on 2024-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='regionType',
            field=models.CharField(choices=[('State', 'State'), ('District', 'District'), ('Community', 'Community'), ('none', None)], max_length=100),
        ),
    ]
