# Generated by Django 5.0.4 on 2024-04-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_region_regiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeAlarms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('type', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('AIR', 'AIR'), ('ARTILLERY', 'ARTILLERY'), ('URBAN_FIGHTS', 'URBAN_FIGHTS'), ('CHEMICAL', 'CHEMICAL'), ('NUCLEAR', 'NUCLEAR'), ('INFO', 'INFO')], max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.region')),
            ],
        ),
    ]
