# Generated by Django 5.0.4 on 2024-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_activealarms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activealarms',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
