# Generated by Django 5.0.4 on 2024-04-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_activealarms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='childrenOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.region'),
        ),
    ]
