# Generated by Django 5.0.4 on 2024-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_region_childrenof'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFcmToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fcmToken', models.CharField(max_length=100)),
                ('expiredAt', models.DateTimeField()),
            ],
        ),
    ]
