# Generated by Django 5.0.4 on 2024-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userfcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='fcmToken',
            field=models.CharField(max_length=500),
        ),
    ]
