# Generated by Django 5.0.4 on 2024-04-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_userfcmtoken_fcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
