# Generated by Django 5.0.4 on 2024-04-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_activealarms_activealarm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveAlarm',
            new_name='activeAlarms',
        ),
    ]
